/**
 * Cross-implementation parity — the drift guard for this package.
 *
 * This package deliberately reuses the wire protocol proven by the /strix-wire
 * skill helper rather than inventing one. That reuse is only safe if it is
 * pinned: three independent implementations of the same byte contract now exist
 * (the Python reference `solo_builder/_canonical.py`, the vendored TS helper at
 * release/strixgov-skills/.../governedAction.ts, and this package via
 * @strixgov/sdk's SCJ v1 mirror), and CJ-1's whole point is that they must be
 * byte-identical. Independent implementations are the moat; drift between them
 * is the only risk.
 *
 * Two things are pinned here:
 *
 *   1. CANONICAL BYTES — this package's canonicalization must agree with the
 *      Python reference that ADR-005 §4 names as the source of truth. If they
 *      disagree on any input, a hash minted through this package would not
 *      reproduce under the reference verifier, and a receipt would be
 *      unverifiable for a reason nobody would think to look for.
 *
 *   2. WIRE CONSTANTS — the four endpoint paths must match the vendored
 *      helper's. A path that drifted would produce a 404 that surfaces as a
 *      generic transport error rather than as "you are talking to the wrong
 *      endpoint".
 *
 * HOW THE REFERENCE IS OBTAINED — and why not by path.
 *
 * This test used to shell out to `python3` against a hardcoded absolute path and
 * hard-FAIL when it was missing, on the reasoning that a conformance check which
 * skips reports green while verifying nothing. The reasoning was right; the
 * mechanism was not. The default path was an absolute Linux path from the
 * authoring sandbox, so `npm test` was red on every other machine — it failed
 * for everyone who was not one specific container, which teaches contributors to
 * ignore a red suite. That is worse than a vacuous skip.
 *
 * Fixed the way this repo already solves it elsewhere: the reference's OUTPUT is
 * vendored as a locked corpus (test/parity-corpus.locked.json), generated BY the
 * Python implementation ADR-005 section 4 names as the source of truth. Same move
 * strix-platform made when the distillation conformance lane's cross-repo
 * checkout failed closed without a token — it vendored the grader into
 * conformance/corpus/distillation_policy_v1/_pyref/ so the lane became
 * self-contained. No Python, no network, no path: green on any machine, and still
 * genuinely pinned, because a canonicalization change here must show up as a diff
 * in a committed file.
 *
 * The live differential is still available and still hard-fails, but only when
 * you opt in by pointing STRIX_PARITY_PY_ROOT at a real reference checkout. That
 * is the lane CI should run; the locked corpus is what protects everyone else.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, '..', '..', '..');

const PY_ROOT = process.env.STRIX_PARITY_PY_ROOT ?? '/home/user/solo-builder-core/src';
const HELPER = join(
  REPO_ROOT,
  'release/strixgov-skills/skills/strix-wire/helpers/governedAction.ts',
);

const { canonicalizeJSONScjV1Mirror } = await import('@strixgov/sdk');

/**
 * A corpus chosen for the cases that actually diverge between naive
 * implementations: key ordering, nesting, non-ASCII (ensure_ascii=False),
 * empty containers, numeric forms, and escape handling.
 */
const CORPUS = [
  {},
  { a: 1 },
  { b: 1, a: 2 },
  { z: 1, a: { z: 1, a: 1 } },
  { nested: [1, { d: 4, c: 3 }, []] },
  { unicode: 'héllo — wörld ✓' },
  { escapes: 'line\nbreak\ttab "quoted" back\\slash' },
  { empty_obj: {}, empty_arr: [] },
  { nullish: null, bool: true, falsey: false },
  { int: 0, neg: -17, float: 1.5 },
  { deep: { a: { b: { c: { d: [1, 2, { e: 'f' }] } } } } },
  // The exact evidenceHash material this package hashes.
  { capabilityId: 'mcp.github.merge_pull_request', evidenceId: 'ev-1', outcome: 'ok', payloadHash: 'abc', resultHash: 'def' },
  // The exact evaluate body shape.
  { capabilityId: 'x.y', actor: { id: 'a', role: 'operator' }, context: { payloadHash: 'h', source: 'governed-action' } },
];

const LOCKED = JSON.parse(
  readFileSync(join(HERE, 'parity-corpus.locked.json'), 'utf8'),
);

test('canonical bytes match the locked reference corpus (ADR-005 §4 / CJ-1)', () => {
  assert.ok(LOCKED.vectors.length > 0, 'locked corpus must not be empty');
  assert.equal(
    LOCKED.sourceFile,
    'src/solo_builder/_canonical.py',
    'corpus must declare which reference implementation produced it',
  );

  for (const [i, v] of LOCKED.vectors.entries()) {
    const mine = canonicalizeJSONScjV1Mirror(v.input);
    assert.equal(
      mine,
      v.canonical,
      `canonical byte divergence on vector ${i} (${JSON.stringify(v.input)}):\n` +
        `  this package: ${mine}\n  reference:    ${v.canonical}`,
    );
  }
});

test('live differential against a real Python checkout (opt-in via STRIX_PARITY_PY_ROOT)', (t) => {
  const pyRoot = process.env.STRIX_PARITY_PY_ROOT;
  if (!pyRoot) {
    // Not a vacuous skip of the CONFORMANCE claim — the test above already
    // checked every vector against the reference's committed output. This lane
    // only re-derives that output live, to catch the reference itself moving.
    t.skip('STRIX_PARITY_PY_ROOT unset — locked-corpus check above covers conformance');
    return;
  }
  assert.ok(
    existsSync(join(pyRoot, 'solo_builder/_canonical.py')),
    `STRIX_PARITY_PY_ROOT is set to ${pyRoot} but no solo_builder/_canonical.py is there. ` +
      'This FAILS rather than skips: you asked for the live differential explicitly.',
  );

  const script = `
import json, sys
sys.path.insert(0, ${JSON.stringify(pyRoot)})
from solo_builder._canonical import canonicalize
for line in sys.stdin:
    line = line.strip()
    if not line:
        continue
    out = canonicalize(json.loads(line))
    sys.stdout.write((out.decode("utf-8") if isinstance(out, bytes) else out) + "\\n")
`;
  const input = LOCKED.vectors.map((v) => JSON.stringify(v.input)).join('\n') + '\n';
  const raw = execFileSync('python3', ['-c', script], { input, encoding: 'utf8' });
  const pythonOut = raw.split('\n').filter((l) => l !== '');

  assert.equal(pythonOut.length, LOCKED.vectors.length, 'reference produced one line per input');
  LOCKED.vectors.forEach((v, i) => {
    assert.equal(
      pythonOut[i],
      v.canonical,
      `the locked corpus has drifted from the live reference on vector ${i}. ` +
        'Either the reference changed (regenerate + gate-review) or the corpus is stale.',
    );
  });
});

test('canonicalization enforces the ADR-005 §4 byte rules', () => {
  // Sorted keys, no whitespace.
  assert.equal(canonicalizeJSONScjV1Mirror({ b: 1, a: 2 }), '{"a":2,"b":1}');
  // Non-ASCII preserved, not \u-escaped (ensure_ascii=False).
  assert.ok(canonicalizeJSONScjV1Mirror({ k: 'é' }).includes('é'));
  // allow_nan=False — a non-finite number must throw, never serialize.
  assert.throws(() => canonicalizeJSONScjV1Mirror({ n: Number.NaN }));
  assert.throws(() => canonicalizeJSONScjV1Mirror({ n: Number.POSITIVE_INFINITY }));
});

test('wire constants match the vendored /strix-wire helper', () => {
  assert.ok(
    existsSync(HELPER),
    `vendored helper not found at ${HELPER} — this package's protocol is defined ` +
      'as matching it, so its absence means the pin cannot be evaluated.',
  );
  const helperSrc = readFileSync(HELPER, 'utf8');
  const mineSrc = readFileSync(join(HERE, '..', 'src', 'index.ts'), 'utf8');

  const read = (src, name) => {
    const m = src.match(new RegExp(`const ${name}\\s*=\\s*["']([^"']+)["']`));
    return m?.[1];
  };

  for (const name of ['DEFAULT_URL', 'EVALUATE_PATH', 'EVIDENCE_PATH', 'SANDBOX_PROVISION_PATH']) {
    const theirs = read(helperSrc, name);
    const mine = read(mineSrc, name);
    assert.ok(theirs, `helper no longer declares ${name}`);
    assert.equal(mine, theirs, `${name} drifted from the vendored helper`);
  }

  // The receipt path is built inline in both; pin the shape rather than a const.
  assert.ok(
    /\/api\/v1\/decisions\/\$\{encodeURIComponent\(decisionId\)\}\/receipt/.test(mineSrc),
    'receipt path must stay /api/v1/decisions/{id}/receipt with the id encoded',
  );
  assert.ok(
    helperSrc.includes('/api/v1/decisions/') && helperSrc.includes('/receipt'),
    'helper receipt path shape changed — re-check parity by hand',
  );
});

test('the verify command stays @latest-pinned (INSTALL-1)', () => {
  const mineSrc = readFileSync(join(HERE, '..', 'src', 'index.ts'), 'utf8');
  assert.ok(
    mineSrc.includes('npx @strixgov/verifier@latest ${signedEvidenceId}'),
    'INSTALL-1 requires the printed verify command carry the @latest pin and be ' +
      'constructed locally rather than taken from the receipt response',
  );
});
