/**
 * Governed Loop v1 — verifier conformance.
 *
 * Proves the independent verifier (`verifyLoop` in src/index.mjs, which
 * re-implements the LP-9 hash chain + LP-7 worst-of terminal state with ZERO
 * shared code) agrees with the solo-builder-core reference signer
 * (`signLoopIntent` / `signLoopIteration`). If the verifier's chain-hash or
 * terminal-state logic drifts from the reference by a single byte or a single
 * precedence rule, this goes red — the entire point of the conformance gate
 * (mirrors swarm-verifier-conformance.test.mjs's discipline).
 *
 * The corpus is VENDORED (fixtures/loop/loop-conformance-vectors.json), signed
 * by the real reference signer with a fixed TEST-ONLY seed and regenerated by
 * fixtures/generate-loop.mjs. This file therefore imports nothing from
 * solo-builder-core.
 *
 * That is deliberate, and it is this package's dominant convention — the
 * trust-mark, disclosure and agent-session suites all replay vendored corpora
 * the same way. Previously this one file imported
 * ../../../solo-builder-core/dist/index.js at module scope, which made the
 * WHOLE verifier suite depend on a built sibling subtree whose dist/ is
 * gitignored and built by no hook: a fresh clone failed here and nowhere else.
 * It also kept this test out of the public release mirror, which carries zero
 * build dependencies — so third parties could replay every other corpus
 * against the independent verifier but not this one.
 *
 * The trade, stated plainly: this suite no longer re-runs the reference signer
 * live, so it cannot notice that solo-builder-core's signer changed. That
 * check moves to regeneration time — re-run generate-loop.mjs after any
 * reference-signer change and review the diff.
 *
 * Uses node:test (no vitest dependency), matching rt-09 / swarm conformance.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { verifyLoop } from "../src/index.mjs";

const __dir = dirname(fileURLToPath(import.meta.url));

const FIXTURE = JSON.parse(
  readFileSync(
    join(__dir, "fixtures", "loop", "loop-conformance-vectors.json"),
    "utf8",
  ),
);

const LOOP_ID = FIXTURE.loopId;
const JWKS = { keys: [FIXTURE.publicJwk] };

/**
 * Fresh deep copy per test. Several cases tamper with the proof in place, and
 * a shared reference would leak that mutation into later tests.
 */
function proofOf(name) {
  const p = FIXTURE.proofs[name];
  assert.ok(p, `fixture proof "${name}" missing — regenerate with generate-loop.mjs`);
  return structuredClone(p);
}

test("chain-only (no --jwks): a valid chain is UNVERIFIABLE, never VERIFIED or INVALID", async () => {
  const r = await verifyLoop(LOOP_ID, { proof: proofOf("chain3") });
  assert.equal(r.chainOk, true);
  assert.equal(r.terminalState, "COMPLETED");
  assert.equal(r.verificationStatus, "UNVERIFIABLE");
  assert.equal(r.reason, "LOOP_SIGNATURES_NOT_CHECKED");
});

test("VERIFIED — with the real JWKS, a valid chain + valid signatures verify", async () => {
  const r = await verifyLoop(LOOP_ID, { proof: proofOf("chain3"), jwks: JWKS });
  assert.equal(r.verificationStatus, "VERIFIED");
  assert.equal(r.chainOk, true);
  assert.equal(r.terminalState, "COMPLETED");
  assert.equal(r.signatures.checked, 4); // 1 intent + 3 iterations
  assert.equal(r.signatures.valid, 4);
  assert.equal(r.counts.iterations, 3);
});

test("INVALID — a tampered iteration payload breaks its own signature", async () => {
  const proof = proofOf("chain2");
  proof.iterations[1].canonical.payload.consumptionSnapshot = { actions: 999 };
  const r = await verifyLoop(LOOP_ID, { proof, jwks: JWKS });
  assert.equal(r.verificationStatus, "INVALID");
  assert.equal(r.reason, "LOOP_SIGNATURE_INVALID");
});

test("INVALID (chain) — a tampered payload also breaks the hash chain, and chain-break wins even with keys", async () => {
  const proof = proofOf("chain3");
  // Tamper the FIRST iteration; the second iteration's priorIterationHash no
  // longer matches, breaking the chain independent of the signature check.
  proof.iterations[0].canonical.payload.consumptionSnapshot = { actions: 999 };
  const r = await verifyLoop(LOOP_ID, { proof, jwks: JWKS });
  assert.equal(r.chainOk, false);
  assert.equal(r.verificationStatus, "INVALID");
  assert.equal(r.reason, "LOOP_CHAIN_BROKEN");
});

test("a blocked branch (denied iteration) never launders into a plain COMPLETED", async () => {
  const r = await verifyLoop(LOOP_ID, {
    proof: proofOf("blockedBranch"),
    jwks: JWKS,
  });
  assert.equal(r.chainOk, true);
  assert.equal(r.terminalState, "COMPLETED_WITH_BLOCKED_BRANCHES");
  assert.equal(r.counts.blockedBranches, 1);
  assert.equal(r.counts.denied, 1);
  assert.equal(r.counts.admitted, 1);
});

test("LEGACY_UNSIGNED — a loop with no iterations yet", async () => {
  const r = await verifyLoop(LOOP_ID, { proof: proofOf("intentOnly") });
  assert.equal(r.verificationStatus, "LEGACY_UNSIGNED");
  assert.equal(r.counts.iterations, 0);
});

test("agreement check: independent verdict compared against the server's claim", async () => {
  const proof = proofOf("chain2");
  proof.verification_status = "VERIFIED";
  const r = await verifyLoop(LOOP_ID, { proof, jwks: JWKS });
  assert.equal(r.serverStatus, "VERIFIED");
  assert.equal(r.agreesWithServer, true);
});

test("the vendored corpus was produced by the reference signer, not re-derived here", async () => {
  // Guard against the corpus silently becoming self-referential: this file
  // must never import solo-builder-core, and the fixture must carry the
  // reproducible TEST-only seed that lets anyone regenerate and compare.
  const self = readFileSync(join(__dir, "loop-verifier-conformance.test.mjs"), "utf8");
  const importsReference = /from\s+["'][^"']*solo-builder-core[^"']*["']/.test(self);
  assert.equal(importsReference, false, "this suite must not import solo-builder-core");
  assert.match(FIXTURE.signingKeySeedHex, /^[0-9a-f]{64}$/);
  assert.equal(FIXTURE.publicJwk.kty, "OKP");
  assert.equal(FIXTURE.publicJwk.crv, "Ed25519");
});
