/**
 * Replays the Strix conformance corpus for `strix-execution-authority-v1`
 * through THIS package's verifier. The corpus is generated by the Strix issuer
 * with a public, test-only key; this package shares no code with it. Every
 * vector must reach the recorded verdict and reason, or the two
 * implementations have drifted and a build fails before a production
 * verification does.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const { verifyGrant, verifyRevocationDocument, spkiFromJwkX, canonicalJson } = await import('../dist/index.js');

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '../../../conformance/corpus');
const GRANT_DIR = path.join(ROOT, 'execution_authority_v1');
const REVOCATION_DIR = path.join(ROOT, 'authority_revocation_v1');

function readIndex(dir) {
  const index = JSON.parse(fs.readFileSync(path.join(dir, 'index.json'), 'utf8'));
  assert.ok(index.vector_count > 0, 'an empty corpus proves nothing');
  assert.equal(index.vectors.length, index.vector_count);
  return index.vectors.map((rel) => JSON.parse(fs.readFileSync(path.join(dir, rel), 'utf8')));
}

test('every execution-authority vector reaches the recorded verdict', () => {
  const vectors = readIndex(GRANT_DIR);
  assert.ok(vectors.some((v) => v.category === 'positive') && vectors.some((v) => v.category === 'negative'));
  for (const v of vectors) {
    const { trust, expected_execution, as_of } = v.verification_inputs;
    const r = verifyGrant(v.grant, trust, expected_execution, new Date(as_of));
    assert.equal(r.valid, v.expected.valid, `${v.vector_id}: ${JSON.stringify(r)}`);
    if (!v.expected.valid) assert.equal(r.reason, v.expected.reason, `${v.vector_id}: ${r.detail}`);
  }
});

test('every revocation vector reaches the recorded verdict', () => {
  const vectors = readIndex(REVOCATION_DIR);
  for (const v of vectors) {
    const { issuer, keys, as_of, min_generation } = v.verification_inputs;
    const trustKeys = keys.map((k) => ({ kid: k.kid, publicKeySpkiBase64: spkiFromJwkX(k.x), status: k.status, notBefore: k.notBefore, notAfter: k.notAfter }));
    const r = verifyRevocationDocument(v.document, { issuer, keys: trustKeys, asOf: new Date(as_of), minGeneration: min_generation });
    assert.equal(r.ok, v.expected.valid, `${v.vector_id}: ${JSON.stringify(r)}`);
    if (!v.expected.valid) assert.equal(r.reason, v.expected.reason, v.vector_id);
  }
});

test('the canonical form is the issuer\'s: sorted keys at every depth, no whitespace, unicode kept', () => {
  assert.equal(canonicalJson({ b: [1, { z: 'ß', a: null }], a: true }), '{"a":true,"b":[1,{"a":null,"z":"ß"}]}');
  assert.throws(() => canonicalJson({ a: Number.NaN }));
  assert.throws(() => canonicalJson({ a: undefined }));
});
